import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<title>Spielberg</title>
			</head>
			<body
				className={`${inter.variable} antialiased font-[Inter] bg-[#161617]`}
			>
				<main className="min-h-screen bg-gray-50 dark:bg-[#161617]">
					<NavBar />

					<div className="w-[1392px] mx-auto h-full pt-[20px]">{children}</div>
				</main>
			</body>
		</html>
	);
}
